# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa9a2d423575f2df308f63b125bcd111a56540f29a921a4636bf87588c090771298a1607346300a05cc458869533d204a23fc086aac48720eadeb0f84abdaa72

test:
  secret_key_base: 8c19cc72e7fa67c90f0d1d7fbe86c99081bf2478adb9d1204f0b1982fadbd6d1452dea912d09e2119e7bb88ffa5146bde287404c53dfdbb3d1724c4574b78f4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
